language: node_js
node_js:
  - stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g typings
  - npm install -g codeclimate-test-reporter
  - typings install
script: node_modules/karma/bin/karma start karma.conf.js --single-run
after_success:
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
addons:
  code_climate:
    repo_token: 9ee391d2668f48d8c3d8a86484bcdcb33a67bef57ae42ac53fcf64901cb71f3c
